### PR TITLE
[14.0][MIG] fieldservice_vehicle_stock

### PR DESCRIPTION
**Pull request by ReedHayashikawa**
Depends on: 
[OCA/stock-logistics-warehouse#1193](https://github.com/OCA/stock-logistics-warehouse/pull/1193)
#730 
#690

### CODE REVIEW

**Comment by patrickrwilson** [comment]
Depends on #821

**Comment by patrickrwilson** [comment]
Depends on https://github.com/OCA/stock-logistics-warehouse/pull/1193

**Comment by Freni-OSI** [comment]
Hi @ReedHayashikawa, Can you please rebase this branch and squash automated commits? so that it can be ready for review. Thanks
CC: @patrickrwilson

**Comment by ReedHayashikawa** [comment]
> Hi @ReedHayashikawa, Can you please rebase this branch and squash automated commits? so that it can be ready for review. Thanks
> CC: @patrickrwilson

@Freni-OSI Thank you. I squashed those commits. 

CC @patrickrwilson

**Comment by patrickrwilson** [comment]
@ReedHayashikawa looks like it's close, just need to adjust the tests as they are some failing in Travis. Thanks

**Review by patrickrwilson — APPROVED** [review]
Thanks for migrating this. LGTM

**Comment by patrickrwilson** [comment]
@osi-scampbell @smangukiya can you please review?

**Review by smangukiya — APPROVED** [review]

**Pull request merged**
