### PR TITLE
[FIX] fieldservice: resource views

### PR DESCRIPTION
**Pull request by brian10048**
Resource calendar views were being overridden by the fsm schedule view

Screenshot from 2020-11-03 10-43-06

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
@brian10048 Good catch. Functional review. :+1:

**Comment by brian10048** [comment]
I had been wondering why I could never configure resource calendars properly!

**Review by marcelsavegnago — APPROVED** [review]

**Comment by dreispt** [comment]
This PR should only be merger on a Friday 13.

**Review by dreispt — APPROVED** [review]

**Comment by brian10048** [comment]
> This PR should only be merger on a Friday 13.

@dreispt - Well it is election day here in the states...

**Pull request merged**
