### PR TITLE
[14.0][MIG] fieldservice_repair

### PR DESCRIPTION
**Pull request by Freni-OSI**
Depends on #818

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Freni-OSI can you increase code coverage tests please.

**Comment by Freni-OSI** [comment]
> @Freni-OSI can you increase code coverage tests please.

Ready for review

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Comment by patrickrwilson** [comment]
@smangukiya @osi-scampbell can you please review?

**Review by smangukiya — APPROVED** [review]

**Pull request merged**
