### PR TITLE
[12.0][FIX] fieldservice_repair

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Depends https://github.com/OCA/field-service/pull/582

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@bodedra If possible, take a look at this PR please.

**Review by eduaparicio — APPROVED** [review]
Functional. 
As a suggestion for the future, the inventory location should not be required. There are cases when the equipment may be on the field (outside the company).

**Comment by marcelsavegnago** [comment]
Hi @osi-scampbell  @bodedra could you please review this PR?

**Comment by marcelsavegnago** [comment]
@jpcarassato Could you please review this PR?

**Comment by bodedra** [comment]
@marcelsavegnago Sorry. I am not available to review this PR.

@patrickrwilson @brian10048 would you guys available for review this?

**Comment by marcelsavegnago** [comment]
> @marcelsavegnago Sorry. I am not available to review this PR.
> 
> @patrickrwilson @brian10048 would you guys available for review this?

@bodedra thanks

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by osi-scampbell — APPROVED** [review]

**Review by nelsonramirezs — APPROVED** [review]
LGTM!

**Pull request merged**
