### PR TITLE
[MIG] fieldservice_route: Migration to v13

### PR DESCRIPTION
**Pull request by chienandalu**
Superseeds

- #613

Forward port of features in:

- [x] #663
- [x] #742

Respecting work and attribution from @nikul-serpentcs but finishing the few points of revision left.

cc @Tecnativa TT31760

ping @brian10048 @max3903 @nikul-serpentcs

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Travis is red

**Comment by chienandalu** [comment]
Ready for review

**Review by brian10048 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Isn't the migration script go out instead of being renamed? Is this including our latest improvements in v12?

**Comment by chienandalu** [comment]
> Isn't the migration script go out instead of being renamed?

Sure, I didn't notice that detail. Removed.

> Is this including our latest improvements in v12?

Yes, I put the migration commit on top of the current branch

**Comment by pedrobaeza** [comment]
Now I see changes in main module in the migration commit.

**Comment by chienandalu** [comment]
You must be seeing changes from this commit which is a lost feature from v12 https://github.com/OCA/field-service/pull/912/commits/9f2119194103342045bd12f49125688520bb3ed3

**Review by pedrobaeza — APPROVED** [review]
Yeah, my bad

**Pull request merged**
