### PR TITLE
[17.0][MIG] fieldservice_route: Migration to 17.0

### PR DESCRIPTION
**Pull request by DiegoFJ95**

### CODE REVIEW

**Comment by SMaciasOSI** [comment]
@max3903 Could you run the tests so we can see where this is failing?

**Review by SMaciasOSI — APPROVED** [review]
@max3903 All checks have passed after a rebase. I have tested this module before and it works as expected

**Review by brian10048 — APPROVED** [review]
Code reviewed and briefly tested on runboat, working as expected

**Pull request merged**
