### PR TITLE
[14.0][MIG] fieldservice_account_analytic

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@brian10048 , @patrickrwilson , @dreispt , @osi-scampbell , @smangukiya , @murtuzasaleh 
This module dependency module was merged can we rebuild Travis and run bot and review this PR

**Comment by patrickrwilson** [comment]
@Freni-OSI can you please squash all the automated commits ([UPD], Translations, .pot).

**Comment by Freni-OSI** [comment]
> @Freni-OSI can you please squash all the automated commits ([UPD], Translations, .pot).

Done. needs review. @patrickrwilson

**Comment by patrickrwilson** [comment]
@Freni-OSI can you increase code coverage tests?

**Review by patrickrwilson — APPROVED** [review]
Tested and works as intended. LGTM

**Review by smangukiya — APPROVED** [review]

**Comment by smangukiya** [comment]
@OCA-git-bot merge nobump

**Pull request merged**
