### PR TITLE
[14.0][IMP] fieldservice_sale: remove required attr in product view

### PR DESCRIPTION
**Pull request by hparfr**
Create a blank fsm from a SO is a valid use case.
And it make more sense when used with fsm_recurring_sale

Implement rfc #735

### CODE REVIEW

**Review by brian10048 — APPROVED** [review]

**Review by smangukiya — APPROVED** [review]
@hparfr : LGTM. Thank you for your contribution.

**Comment by smangukiya** [comment]
@brian10048 : Would you go ahead and merge this PR or do you want me to? Thanks for your great contribution as always :)

**Comment by smangukiya** [comment]
@hparfr : Thanks for your contribution! Appreciated.

**Pull request merged**
