### PR TITLE
[13.0][MIG] fieldservice_project

### PR DESCRIPTION
**Pull request by baimont**
Migration of fieldservice_project to 13.0

https://github.com/OCA/field-service/issues/354

I'll add tests when I find some time.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@baimont Very good work. Can you implement some tests to improve coverage?

**Review by brian10048 — APPROVED** [review]
Awesome work on the test coverage.  Greatly appreciated

**Comment by marcelsavegnago** [comment]
@baimont Very good! Thanks. Congratulations

**Review by marcelsavegnago — APPROVED** [review]

**Review by bodedra — COMMENTED** [review]
Code review and functional testing at runbot http://3479579-772-d64219.runbot1-2.odoo-community.org/web

Project > FSM order failed to carry default project. It remains empty.

Tasks > FSM order works well, carry default tasks and assign it correctly.

**Comment by brian10048** [comment]
Thanks for the thorough review @bodedra.  I guess I merged this one a little too soon. 

I opened #774 to help us keep track.  I tested on v12 runbot and it appears the bug is there as well.

**Comment by bodedra** [comment]
Thanks for reporting issue @brian10048 

I feel I reviewed little late. :smile:

**Pull request merged**
