### PR TITLE
[FIX] Travis and Runbot errors

### PR DESCRIPTION
**Pull request by max3903**
... so the pot files can be generated and pushed to https://translation.odoo-community.org

### CODE REVIEW

**Comment by osi-scampbell** [comment]
@max3903 Rebased branch, only squashed the back half of the commits so I can see the differences between the main modules. Waiting on travis build to finish, when all the fsm tests pass I will squash the remainder of the commits 👍

**Comment by dreispt** [comment]
The build failed. I restarted it.

**Comment by dreispt** [comment]
Runbot build fails because:
```
2019-10-24 16:18:55,218 180 INFO openerp_test odoo.modules.registry: module fieldservice_account: creating or updating database tables
2019-10-24 16:18:55,262 180 ERROR openerp_test odoo.sql_db: bad query: ALTER TABLE "fsm_location" ALTER COLUMN "customer_id" SET NOT NULL
ERROR: column "customer_id" contains null values

2019-10-24 16:18:55,262 180 WARNING openerp_test odoo.schema: Table 'fsm_location': unable to set NOT NULL on column 'customer_id'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "fsm_location" ALTER COLUMN "customer_id" SET NOT NULL
Traceback (most recent call last):
File "/home/odoo/OCB-12.0/odoo/tools/sql.py", line 109, in set_not_null
cr.execute(query)
File "/home/odoo/OCB-12.0/odoo/sql_db.py", line 148, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/OCB-12.0/odoo/sql_db.py", line 225, in execute
res = self._obj.execute(query, params)
psycopg2.IntegrityError: column "customer_id" contains null values
```

**Comment by max3903** [comment]
Once merged, this should generate the pot files for translations and push them to Weblate (https://translation.odoo-community.org)

**Comment by dreispt** [comment]
I have a concern about this PR being too big and doing too much stuff.
And I'm not talking about labels and code style fixes:
It includes significant changes to code logic, probably to fix tests, that would be better in their own PRs.

On the other hand I want to see the build fixed ASAP.
What do you think @max3903 ?

**Comment by max3903** [comment]
@dreispt I don't think there is any change to code logic.

**Review by patrickrwilson — APPROVED** [review]
I agree this is a large PR but I also don't see any logic changes. I have no other suggestions. Good work.

**Review by osi-scampbell — APPROVED** [review]

**Pull request merged**
