### PR TITLE
[14.0][MIG] fieldservice_purchase : Migrated the module in v14.

### PR DESCRIPTION
**Pull request by Khalid-SerpentCS**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Freni-OSI please add tests for code coverage. Thanks

**Comment by Vimal-OSI** [comment]
> @Freni-OSI please add tests for code coverage. Thanks

@patrickrwilson , Added test cases, Can you please review it ?
Thanks

**Review by patrickrwilson — APPROVED** [review]
Works as described and code looks good. LGTM

**Pull request merged**
