### PR TITLE
[IMP][11.0] fieldservice_sale

### PR DESCRIPTION
**Pull request by brian10048**
For #202 

- Added ability to link a product with FSM order template and create FSM orders upon sale order confirmation
- Added option to install fieldservice_sale module

### CODE REVIEW

**Comment by brian10048** [comment]
Now that the PR #179 was merged for recurring orders, I will need to resolve conflict in res_config_settings and I can add ability to also sell the recurring field service orders.

**Comment by max3903** [comment]
@brian10048 Can you fix the Travis errors?

**Comment by brian10048** [comment]
@max3903 Travis errors fixed among a few other issues.  Tested and working as intended.

**Comment by max3903** [comment]
@brian10048 Can you add an access rule for `fsm.frequency.set`?

https://travis-ci.org/OCA/field-service/jobs/536512804#L9764

**Comment by brian10048** [comment]
@max3903 Sorry to have missed that one. Access Rule added

**Review by max3903 — APPROVED** [review]

**Pull request merged**
