### PR TITLE
[14.0] [IMP] fieldservice: toggle active FSMPerson

### PR DESCRIPTION
**Pull request by brian10048**
This PR allows you to archive field service workers, while keeping the associated partner active

**Archive button added to worker form**
Screenshot from 2021-11-09 10-23-27

**Form after a worker is archived**
Screenshot from 2021-11-09 10-23-36

### CODE REVIEW

**Comment by smangukiya** [comment]
@brian10048 : Thanks for the contribution, can you please help providing business logic behind this need? Thank you

**Comment by brian10048** [comment]
If a field service worker is terminated from the company, we no longer want the users to be able to select that worker for field service orders.

Currently, the only way to remove the worker is to archive the associated partner.  However we may not want to archive the partner record in case we have other open transactions with that partner.

This feature is adapted from core Odoo, where we can archive an employee without archiving the partner record associated to that employee.

**Comment by smangukiya** [comment]
> If a field service worker is terminated from the company, we no longer want the users to be able to select that worker for field service orders.
> 
> Currently, the only way to remove the worker is to archive the associated partner. However we may not want to archive the partner record in case we have other open transactions with that partner.
> 
> This feature is adapted from core Odoo, where we can archive an employee without archiving the partner record associated to that employee.

Understood. Thank you for the explanation.

**Review by smangukiya — APPROVED** [review]
LGTM

**Comment by brian10048** [comment]
Added tests to original commit

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
@brian10048 pre-commit needs fixing

**Comment by brian10048** [comment]
@dreispt pre-commit runs successfully for me locally.  I think there is an issue with the github actions

https://github.com/OCA/field-service/runs/4288441224?check_suite_focus=true#step:4:54

**Comment by dreispt** [comment]
Can you try rebasing on top of latest 14.0? That sometimes solves this kind of error.
Thanks

**Comment by brian10048** [comment]
Thanks @dreispt - All green now!

**Pull request merged**
