### PR TITLE
[16.0][MIG] fieldservice_isp_account

### PR DESCRIPTION
**Pull request by michelerusti**
migration for #963 

Depends on:

- [x] https://github.com/OCA/field-service/pull/1127

### CODE REVIEW

**Comment by michelerusti** [comment]
There are a bunch of errors regarding wrong INSERT and `not-null constraint` like this one:
[https://github.com/OCA/field-service/actions/runs/6851350407/job/18627432083?pr=1126#step:8:628](https://github.com/OCA/field-service/actions/runs/6851350407/job/18627432083?pr=1126#step:8:628)
`psycopg2.errors.NotNullViolation: null value in column "sale_line_warn" violates not-null constraint
DETAIL: ....
`


 
After some analysis, I conclude that those are not actually module related errors but are environment-caused. Correct me if I'm wrong please:
The failing tests are (taking the link above as an example) in `fieldservice_project` that errors out for the missing, required field,  `customer_id` that is defined in [fieldservice_account_analytic in this PR](https://github.com/OCA/field-service/pull/1127/files#diff-0f010bbc8160334c11b2a99d4e000e11ece3e80db8f2d20393bfdacec2fc7c55R15) and not at all related to **isp_account** and that shouldn't fail in any case since the `owner_id` is [passed as a value in the create](https://github.com/OCA/field-service/blob/bba0b25df572ed103dd2d3549d66a39f24b4ad92/fieldservice_project/tests/common.py#L13)
This is already suspect since those errors are not present in that PR's tests

After a bit of trial and error, I managed to have the expected result, meaning all the errors are related to the module of this PR

How?
Not installing **fieldservice_account_analytic** in the database initialization stage but in the "Run test" stage
By doing so, the tests pass correctly and I've fixed all the one that required to

Why?
idk, somehow if installed before, the database structure changes accordingly (hence the db errors) but the model and the python code is not loaded correctly. I haven't found out why

As per this PR, all the failing tests right now are to be considered junk. 


@max3903 @brian10048 do you have any consideration about this? Am I right in some way or I'm doing something wrong?
Thanks

**Review by stevech091 — APPROVED** [review]
Functional TEST Ok

**Review by are-agilebg — APPROVED** [review]

**Pull request merged**
