### PR TITLE
[IMP] fieldservice_substatus

### PR DESCRIPTION
**Pull request by brian10048**
@max3903 please review for #130 and #131

### CODE REVIEW

**Comment by bodedra** [comment]
@brian10048 Appreciate your efforts on these module. I have improved few items and fixed travis-ci at https://github.com/brian10048/field-service/pull/3

**Review by bodedra — APPROVED** [review]
Code Review :+1:

**Comment by bodedra** [comment]
@brian10048 I have improved module with following points. Would you please take a look at https://github.com/brian10048/field-service/pull/4

- [x] On fsm.stage, add a required many2one field 'Default Sub-Status' to fsm.stage.status
- [x] On fsm.stage, add a required many2many field 'Potential Sub-Statuses' to fsm.stage.status. The Default Sub-Status is automatically added to the list of potential sub-statuses.
- [x] On fsm.order, add a required many2one field 'Sub-Status' to fsm.stage.status. The default value is the default sub-status of the New stage.
- [x] On fsm.order, the list of sub-statuses is filtered based on the stage and its potential sub-statuses.
- [x] On fsm.order, when the stage is updated, the sub-status is set to the default sub-status of the new stage.

CC @max3903

**Comment by max3903** [comment]
@brian10048 @bodedra Thank you!

**Comment by brian10048** [comment]
@bodedra did the hard parts!  Working as anticipated on my end

**Pull request closed without merging**
