### PR TITLE
[12.0][IMP] fieldservice_account, add test scripts

### PR DESCRIPTION
**Pull request by kittiu**
Done!

### CODE REVIEW

**Comment by kittiu** [comment]
Hi, there seem to be many error from other addons, so the travis do not pass.

**Comment by max3903** [comment]
@kittiu Can you rebase please? A couple of those Travis errors should be fixed now.

**Comment by kittiu** [comment]
> @kittiu Can you rebase please? A couple of those Travis errors should be fixed now.

Done rebase.

**Comment by max3903** [comment]
@kittiu Can you fix the Travis errors please?
https://travis-ci.org/OCA/field-service/jobs/555871015#L1174

**Comment by kittiu** [comment]
> @kittiu Can you fix the Travis errors please?
> https://travis-ci.org/OCA/field-service/jobs/555871015#L1174

Fixed. Thank you.

**Pull request merged**
