### PR TITLE
[MIG][12.0] fieldservice_agreement

### PR DESCRIPTION
**Pull request by murtuzasaleh**
WIP

### CODE REVIEW

**Comment by murtuzasaleh** [comment]
@max3903 Can you please review this PR.

**Comment by max3903** [comment]
@murtuzasaleh Please squash your changes.

**Review by max3903 — APPROVED** [review]

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh Please squash your changes.

Done

**Comment by murtuzasaleh** [comment]
@osi-scampbell Can you please review this PR.

**Review by osi-scampbell — APPROVED** [review]

**Pull request merged**
