### PR TITLE
[16.0][MIG] fieldservice_isp_flow: Migration to 16.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 16.0

cc https://github.com/APSL 153657

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

Issue: https://github.com/OCA/field-service/issues/963

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by miquelalzanillas — APPROVED** [review]
Functionally working.

**Comment by miquelpascual** [comment]
It works correctly

**Review by mpascuall — APPROVED** [review]

**Pull request merged**
