### PR TITLE
[12.0][IMP] fieldservice: Add tests

### PR DESCRIPTION
**Pull request by kittiu**
Work in progress. I will keep adding more test in each commit. Please feel free to comment/suggest.

Following are models that I think has reasonable logic to get tested
- [X] revise test_fsm_wizard
- [X] test_fsm_equipment
- [X] test_fsm_location
- [x] test_fsm_person
- [x] test_fsm_team
- [x] test_fsm_order

### CODE REVIEW

**Comment by kittiu** [comment]
@max3903 while writing test, I see in fsm_order.py still use old style of data string, i.e.,
https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_order.py#L25
Should I open separate PR to change this?

**Comment by kittiu** [comment]
@max3903 I found that, this try to ensure that
`scheduled_date_end = scheduled_date_start + scheduled_duration`
https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_order.py#L196-L212
But when code with write(), it looks complicated. Any reason why we don't use compute field with reverse and store=True for scheduled_date_end?
Can I open separate PR to change this?

**Comment by kittiu** [comment]
The test script of this module is pretty much done. Awaiting some comments from following issues,
https://github.com/OCA/field-service/issues/263
https://github.com/OCA/field-service/issues/264
https://github.com/OCA/field-service/issues/265
https://github.com/OCA/field-service/issues/266

All of which, if identified, I can help in fixing. Then, I can complete this PR after that. Thanks!

**Review by osi-scampbell — APPROVED** [review]

**Comment by osi-scampbell** [comment]
@kittiu Test cases look great, it Travis is showing some errors though. The lint errors for fieldservice_maintenance were fixed here: https://github.com/OCA/field-service/pull/270 and the lint errors for fieldservice_repair were fixed here: https://github.com/OCA/field-service/pull/269. The other ones are in fsm_order and they just look like a few unneccary imports. Can you take care of those please?

**Comment by kittiu** [comment]
@osi-scampbell Done as requested. Also rebased and squashed.

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@kittiu Is it still WIP or are you ready to get this merged?

**Comment by kittiu** [comment]
This is ready! @max3903

**Pull request merged**
