### PR TITLE
[14.0][MIG] fieldservice_stock_account_analytic

### PR DESCRIPTION
**Pull request by Vimal-OSI**
Dependency:

- [x] https://github.com/OCA/field-service/pull/763
- [x] https://github.com/OCA/field-service/pull/823
- [x] https://github.com/OCA/stock-logistics-warehouse/pull/1317

### CODE REVIEW

**Comment by Freni-OSI** [comment]
@max3903 It's ready for review

**Review by nikul-serpentcs — APPROVED** [review]
Code  LGTM :+1: 

@max3903 @brian10048 can you please check it?

**Review by max3903 — APPROVED** [review]

**Pull request merged**
