### PR TITLE
[IMP] fieldservice: Location Report and Fix Context

### PR DESCRIPTION
**Pull request by osi-scampbell**
This PR adds Location reports that count the number of locations in their respective stages. It also fixes a bug where creating sub-locations, equipment, and contacts were not having their proper parent or location set properly.

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by patrickrwilson** [comment]
@osi-scampbell this might be my own environment so i need confirmation this isn't an issue with my setup. When i go to create a sub location, and saved, i got the error below. I also get this now when I go to the parent and click the smart button.

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1032, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x0C925E70>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 970, in __get__
    value = record.env.cache.get(record, self)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 1034, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('fsm.location(1025,).serviceprofile_ids', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\models.py", line 2768, in read
    values[name] = field.convert_to_read(record[name], record, use_name_get)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\models.py", line 5039, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 974, in __get__
    self.determine_value(record)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1085, in determine_value
    self.compute_value(recs)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1041, in compute_value
    self._compute_value(records)
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 1032, in _compute_value
    getattr(records, self.compute)()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\fieldservice_agreement\models\fsm_location.py", line 18, in _compute_service_ids
    search([('fsm_location_id', '=', self.id)])
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\fields.py", line 2811, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: fsm.location(1025, 10)

**Comment by osi-scampbell** [comment]
@patrickrwilson  That doesn't seem like an environment issue that looks like a bug. I'll try to replicate it on my machine. Moving PR back to [WIP].

**Comment by osi-scampbell** [comment]
@patrickrwilson So the bug appears to be coming from fieldservice_agreement, when you open a location the method is called and self should only be that record. None the less, I believe there is a misstep in the code where self.id should say loc.id. If you uninstall that module then it should work. I'll go ahead and make a PR in fieldservice_agreement so that error doesn't show up.

**Review by patrickrwilson — APPROVED** [review]
@osi-scampbell i confirmed it was with the fieldservice_agreement module. I started a new db and just installed this update, and it worked fine, once i installed the fieldservice_agreement it provided the errors. This is good to go.

**Review by smangukiya — APPROVED** [review]
Looks good to me

**Pull request merged**
