### PR TITLE
[13.0] [MIG] fieldservice_crm

### PR DESCRIPTION
**Pull request by brian10048**
Migration to 13.0 for fieldservice_crm

#354

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
LGTM
The .pot and .po files still reference version 12.0, i'm not familiar with what these are for but I assume they are auto generated files that will get updated? If not, they probably should be changed to 13.0.

**Comment by brian10048** [comment]
Thank you! They are the translation files. I believe they get automatically changed to 13.0 once merged

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Pull request merged**
