### PR TITLE
[IMP][12.0] fieldservice - Timeline 

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
### FieldService: Scheduled Start - End times
Improved the calculation of scheduled dates and duration

### CODE REVIEW

**Review by wolfhall — APPROVED** [review]
Looks good- ready for functional testing

**Comment by brian10048** [comment]
Can you explain more what we are trying to accomplish with this PR?  Does it help calculate more precise times?

The test is failing [here](https://github.com/OCA/field-service/blob/12.0/fieldservice/tests/test_fsm_order.py#L64).  I'm not sure if the failure is due to this change or if the test case has errors.  I don't understand the reason for Line 61-62 in that test and it may be throwing things off

**Review by hparfr — CHANGES_REQUESTED** [review]
Thanks for this contribution.

Please refactor it: this function is too long and contains code duplication.

**Comment by hpatelserpentcs** [comment]
Hello @brian10048 

> Can you explain more what we are trying to accomplish with this PR? Does it help calculate more precise times?
> 
> The test is failing [here](https://github.com/OCA/field-service/blob/12.0/fieldservice/tests/test_fsm_order.py#L64). I'm not sure if the failure is due to this change or if the test case has errors. I don't understand the reason for Line 61-62 in that test and it may be throwing things off

This calcultion for updates to the fms order form data and also update the timeline. when we updated the duration from timeline it not affected to order.

I will update UT.

**Comment by hpatelserpentcs** [comment]
> Thanks for this contribution.
> 
> Please refactor it: this function is too long and contains code duplication.

I will improve the code

**Comment by hpatelserpentcs** [comment]
@max3903 

I have updated code and UT please review it.

CC @smangukiya @brian10048 @hparfr

**Review by smangukiya — APPROVED** [review]
The code looks good to me. Not Tested.

**Review by brian10048 — APPROVED** [review]

**Pull request merged**
