### PR TITLE
[FIX] fieldservice_account_analytic: automatically fill Contact in FSM Order

### PR DESCRIPTION
**Pull request by tafaRU**
Start by saying that the logical behind it is not clear to me, during a debug session I noticed the following problem.

## To Reproduce

1. create a FSM order
2. set `location_id` field
3. edit the FSM order and save it

**Expected behavior**
Contact is automatically filled with that one of the Location.

**Additional context**
In debug we have:

```
> "customer_id" not in vals and order.customer_id is False
> False

> "customer_id" not in vals and not order.customer_id
> True
```

### CODE REVIEW

**Comment by tafaRU** [comment]
Tests are failing due to https://github.com/OCA/field-service/blob/cf1f50e498036043ac08c41ed3ac803fdef1f446/fieldservice_stock_account/models/fsm_order.py#L52 is no longer raised.
@OCA/field-service-maintainers  is it reasonable to fix them by removing `assertRaises` [here](https://github.com/OCA/field-service/blob/1762aaefedf17677279ca3d94f64980a553e8c9e/fieldservice_stock_account/tests/test_fsm_stock_account.py#L80)?

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
> @OCA/field-service-maintainers is it reasonable to fix them by removing `assertRaises` [here](https://github.com/OCA/field-service/blob/1762aaefedf17677279ca3d94f64980a553e8c9e/fieldservice_stock_account/tests/test_fsm_stock_account.py#L80)?

:+1:

**Review by hparfr — APPROVED** [review]

**Comment by tafaRU** [comment]
@OCA/field-service-maintainers the PR now should be ready to be merged. Thank you in advance!

**Review by max3903 — APPROVED** [review]

**Pull request merged**
