### PR TITLE
[IMP] fieldservice_route: Limit the number of day routes

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by nelsonramirezs — APPROVED** [review]

**Review by nelsonramirezs — APPROVED** [review]

**Review by nelsonramirezs — APPROVED** [review]

**Review by brian10048 — APPROVED** [review]
Good additions. Code review only.  Not tested

**Comment by dreispt** [comment]
@max3903 Tests are failing.

**Review by bodedra — APPROVED** [review]

**Comment by dreispt** [comment]
Travis tests are failing: 
`odoo.exceptions.ValidationError: ("Cannot move to Complete until 'Employee Timesheets' is filled in", None)`
https://travis-ci.org/github/OCA/field-service/jobs/736152923#L2600

**Pull request closed without merging**
