### PR TITLE
[13.0] [MIG] fieldservice_stage_server_action

### PR DESCRIPTION
**Pull request by brian10048**
Migration to 13.0 for #354

### CODE REVIEW

**Comment by bodedra** [comment]
@brian10048 Thanks for migration. This PR depends on "fieldservice_substatus" module. And it is not available in v13 yet. So first we have to migrate it and rebase this PR.

**Comment by brian10048** [comment]
Thanks @bodedra 
I hadn't noticed that error yet, so I will migrate it soon!

**Comment by brian10048** [comment]
@bodedra I proposed a change in 12.0 that can remove this dependency without any adverse effects

#605

**Review by dreispt — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
