### PR TITLE
[14.0][MIG] fieldservice_stock_account

### PR DESCRIPTION
**Pull request by Freni-OSI**
Dependency:

- [x] https://github.com/OCA/field-service/pull/813
- [x] https://github.com/OCA/account-invoice-reporting/pull/186

### CODE REVIEW

**Comment by Freni-OSI** [comment]
@max3903  It's ready for review.

**Review by nikul-serpentcs — APPROVED** [review]
Code LGTM :+1: 

@max3903 @brian10048 Can you please take a look?

Ready to merge :rocket:

**Review by max3903 — APPROVED** [review]

**Pull request merged**
