### PR TITLE
[17.0][MIG] fieldservice_portal: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 162628
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/field-service/issues/1132

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@peluko00 Not a show stopper, but if you can add some description and the FSM icon on the portal that would look much nicer and consistent:
image

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Comment by peluko00** [comment]
> @peluko00 Not a show stopper, but if you can add some description and the FSM icon on the portal that would look much nicer and consistent: image

Done, thanks!

**Review by BernatObrador — APPROVED** [review]
LGTM!

**Review by ivantodorovich — APPROVED** [review]
Technically LG.

Could you check the pre-commit issue? CI is red due to this

```
****po-syntax-error****
fieldservice_portal/i18n/es.po:1 Syntax error in po file (line 67): unescaped double quote found - [po-syntax-error]
```

**Review by marcelsavegnago — APPROVED** [review]

**Comment by peluko00** [comment]
@max3903 seems it's ready to merge

**Comment by ivantodorovich** [comment]
Actually, @peluko00 , there's still the `pre-commit` issue I mentioned on my last comment.

```
****po-syntax-error****
fieldservice_portal/i18n/es.po:1 Syntax error in po file (line 67): unescaped double quote found - [po-syntax-error]
```

https://github.com/OCA/field-service/actions/runs/11589402819/job/32264841574?pr=1252

Could you check it out?

**Comment by peluko00** [comment]
> Actually, @peluko00 , there's still the `pre-commit` issue I mentioned on my last comment.
> 
> ```
> ****po-syntax-error****
> fieldservice_portal/i18n/es.po:1 Syntax error in po file (line 67): unescaped double quote found - [po-syntax-error]
> ```
> 
> https://github.com/OCA/field-service/actions/runs/11589402819/job/32264841574?pr=1252
> 
> Could you check it out?

Done, can you retry? Thanks! @ivantodorovich

**Comment by ivantodorovich** [comment]
Looks good now 👍🏻 
Thanks a lot! ❤️ 

I have no merge powers here, but I'm sure someone from the PSC will merge it asap

**Pull request merged**
