### PR TITLE
[14.0][MIG]fieldservice_activity

### PR DESCRIPTION
**Pull request by Chanakya-OSI**

### CODE REVIEW

**Comment by brian10048** [comment]
Hello @Chanakya-OSI
This should be ready to migrate now as base fieldservice v14 is merged.  

Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch for instructions.  It is important to use the `git format-patch` command to keep the previous commit history for this module

**Comment by osi-scampbell** [comment]
@Chanakya-OSI Is this still a Draft PR? How long until this is ready?

**Comment by patrickrwilson** [comment]
@Chanakya-OSI Can you squash the automated commits in the history please. (All the translation, .pot and readme update commits) Then I'll review.

**Comment by smangukiya** [comment]
@Chanakya-OSI : Can you attend previous feedback from @patrickrwilson  Thanks

**Pull request merged**
