### PR TITLE
[12.0][ADD] fieldservice_stock_account

### PR DESCRIPTION
**Pull request by bodedra**
Issue Reference: https://github.com/OCA/field-service/issues/297

Depends on :
- [x] #238 
- [x] #305

CC @max3903

### CODE REVIEW

**Comment by bodedra** [comment]
@osi-scampbell @brian10048 are you guys available for review these ?

**Review by max3903 — APPROVED** [review]

**Comment by brian10048** [comment]
@max3903 @bodedra 

I might not have configured something properly or I am misunderstanding the intended purpose.

In the issue reference #297, after validating the invoice the expectation is 

> Check the accounting entry to make sure the value of the inventory items is accounted as a cost of goods/services sold.

The journal entry I get shows the product as a label with its income (sales) account rather than an expense (cost of goods) account.  The value is also 0.  How are we to account for the cost using the income account for that product and a value of 0?  For the invoice purpose I understand we aren't charging specifically for the product so it needs to be 0 on the invoice, but how will this allow tracking its cost in the invoice's journal entry?

**Comment by max3903** [comment]
@brian10048 Did you activate the anglo-saxon accounting?

**Comment by brian10048** [comment]
@max3903 
I installed the US Chart of Accounts module, so this means Anglo-Saxon is activated, correct?

After looking further, would I need to be using a product with 'automated' inventory valuation, not 'manual'?

**Comment by max3903** [comment]
@brian10048 Yes and yes

**Review by brian10048 — APPROVED** [review]
Tested and working as intended

**Pull request merged**
