### PR TITLE
[IMP][14.0] fieldservice

### PR DESCRIPTION
**Pull request by Vandan-OSI**
User unable to create FSM Location from Master Data> Location > Create 
Improved fsm.location code for creation of Location.
Screenshot-from-2022-01-17-15-40-11

### CODE REVIEW

**Comment by TheCloneMaster** [comment]
The same has to be applied to fsm_person...

**Comment by smangukiya** [comment]
@Vandan-OSI Can you also apply this fix for fieldservice worker? check this issue https://github.com/OCA/field-service/issues/907 reported by @dreispt 
Thank you

**Review by mymage — APPROVED** [review]
LGTM

**Comment by mymage** [comment]
> @Vandan-OSI Can you also apply this fix for fieldservice worker? check this issue #907 reported by @dreispt Thank you

I did an emergency call to solve it #911 ;-)

**Pull request merged**
