### PR TITLE
[MIG][18.0]fieldservice_account

### PR DESCRIPTION
**Pull request by EdgarRetes**
@max3903

### CODE REVIEW

**Comment by brian10048** [comment]
@EdgarRetes I'll be glad to help review all of your 18.0 migration PRs if you can rebase them now that core fieldservice module is merged

**Comment by EdgarRetes** [comment]
@brian10048 can you test this?

**Review by brian10048 — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
