### PR TITLE
[14.0][MIG] fieldservice_fleet

### PR DESCRIPTION
**Pull request by Khalid-SerpentCS**

### CODE REVIEW

**Comment by Freni-OSI** [comment]
test cases of hook are failing. Needs review
CC: @patrickrwilson

**Comment by patrickrwilson** [comment]
@Freni-OSI maybe this will help, you can look here as an example of a test for pre-hook? https://github.com/OCA/product-attribute/blob/14.0/product_sequence/tests/test_product_sequence.py#:~:text=def%20test_pre_init_hook(self)%3A

**Comment by Freni-OSI** [comment]
@max3903 Can you please review this PR?

**Review by max3903 — APPROVED** [review]

**Pull request merged**
