### PR TITLE
[15.0][MIG] fieldservice_account_payment

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@brian10048 @max3903 can you please take a look?

**Review by max3903 — APPROVED** [review]

**Review by murtuzasaleh — APPROVED** [review]

**Review by nikul-serpentcs — APPROVED** [review]
Code LGTM :+1: 

Ready to merge

**Comment by Freni-OSI** [comment]
@brian10048 can you please review this PR?
CC: @max3903

**Pull request merged**
