### PR TITLE
[IMP] fieldservice_stage_server_action: Add a mixin to call server action when stage changes on different field service models

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Review by Camille0907 — APPROVED** [review]
LGTM, thank you :+1:

**Review by gurneyalex — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Comment by brian10048** [comment]
@yankinmax I am having an issue testing this module in runboat 

### Configuration:
**Server Action**
image

**Order Stage**
image


### Steps to Reproduce

1. Create a new order.
2. Attempt to change stage of order to Confirmed stage
3. Receive error:

> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 1783, in _serve_db
>     return service_model.retrying(self._serve_ir_http, self.env)
>   File "/opt/odoo/odoo/service/model.py", line 133, in retrying
>     result = func()
>   File "/opt/odoo/odoo/http.py", line 1810, in _serve_ir_http
>     response = self.dispatcher.dispatch(rule.endpoint, args)
>   File "/opt/odoo/odoo/http.py", line 2014, in dispatch
>     result = self.request.registry['ir.http']._dispatch(endpoint)
>   File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
>     result = endpoint(**request.params)
>   File "/opt/odoo/odoo/http.py", line 759, in route_wrapper
>     result = endpoint(self, *args, **params_ok)
>   File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 468, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/addons/web/models/models.py", line 71, in web_save
>     self.write(vals)
>   File "/opt/odoo/addons/base_automation/models/base_automation.py", line 749, in write
>     write.origin(self.with_env(automations.env), vals, **kw)
>   File "/mnt/data/odoo-addons-dir/fieldservice_account_analytic/models/fsm_order.py", line 36, in write
>     res = super().write(vals)
>   File "/mnt/data/odoo-addons-dir/fieldservice_route/models/fsm_order.py", line 107, in write
>     return super().write(vals)
>   File "/mnt/data/odoo-addons-dir/fieldservice_calendar/models/fsm_order.py", line 59, in write
>     res = super().write(vals)
>   File "/mnt/data/odoo-addons-dir/fieldservice/models/fsm_order.py", line 269, in write
>     res = super().write(vals)
>   File "/opt/odoo/addons/mail/models/mail_thread.py", line 317, in write
>     result = super(MailThread, self).write(values)
>   File "/opt/odoo/addons/mail/models/mail_activity_mixin.py", line 250, in write
>     return super(MailActivityMixin, self).write(vals)
>   File "/mnt/data/odoo-addons-dir/fieldservice_stage_server_action/models/fsm_stage_server_action_mixin.py", line 20, in write
>     self._run_stage_server_action()
>   File "/mnt/data/odoo-addons-dir/fieldservice_stage_server_action/models/fsm_stage_server_action_mixin.py", line 32, in _run_stage_server_action
>     action_id.with_context(**ctx).run()
>   File "/opt/odoo/odoo/addons/base/models/ir_actions.py", line 951, in run
>     res = runner(run_self, eval_context=eval_context)
>   File "/opt/odoo/addons/mail/models/ir_actions_server.py", line 283, in _run_action_next_activity
>     record.activity_schedule(**vals)
>   File "/opt/odoo/addons/mail/models/mail_activity_mixin.py", line 399, in activity_schedule
>     return self.env['mail.activity'].create(create_vals_list)
>   File "<decorator-gen-146>", line 2, in create
>   File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
>     return create(self, arg)
>   File "/opt/odoo/addons/mail/models/mail_activity.py", line 324, in create
>     activities = super(MailActivity, self).create(vals_list)
>   File "<decorator-gen-12>", line 2, in create
>   File "/opt/odoo/odoo/api.py", line 415, in _model_create_multi
>     return create(self, arg)
>   File "/opt/odoo/odoo/models.py", line 4565, in create
>     new_vals_list = self._prepare_create_values(vals_list)
>   File "/opt/odoo/odoo/models.py", line 4732, in _prepare_create_values
>     self._add_precomputed_values(result_vals_list)
>   File "/opt/odoo/odoo/models.py", line 4760, in _add_precomputed_values
>     records = self.browse().concat(*(self.new(vals) for vals in vals_list_todo))
>   File "/opt/odoo/odoo/models.py", line 4760, in <genexpr>
>     records = self.browse().concat(*(self.new(vals) for vals in vals_list_todo))
>   File "/opt/odoo/odoo/models.py", line 6456, in new
>     record._update_cache(values, validate=False)
>   File "/opt/odoo/odoo/models.py", line 6022, in _update_cache
>     value = field.convert_to_cache(value, self, validate)
>   File "/opt/odoo/odoo/fields.py", line 3216, in convert_to_cache
>     return super().convert_to_cache(value, record, validate)
>   File "/opt/odoo/odoo/fields.py", line 1441, in convert_to_cache
>     return int(value or 0)
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

**Comment by yankinmax** [comment]
@brian10048 fixed!

**Review by brian10048 — APPROVED** [review]
Working great now

**Pull request merged**
