### PR TITLE
[MIG] fieldservice_sale_recurring

### PR DESCRIPTION
**Pull request by aiendry-aktivsoftware**
Standard migration to 16.0
Depends on below PR
- [16.0 mig fieldservice recurring](https://github.com/OCA/field-service/pull/1096)
- [[16.0][MIG] fieldservice_sale](https://github.com/OCA/field-service/pull/1041)

### CODE REVIEW

**Comment by brian10048** [comment]
@aiendry-aktivsoftware can you fix pre-commit errors?

**Comment by SMaciasOSI** [comment]
@brian10048 Has this PR been replaced by #1149 ?

**Comment by brian10048** [comment]
yes

**Pull request closed without merging**
