### PR TITLE
[13.0] [MIG] fieldservice_maintenance

### PR DESCRIPTION
**Pull request by RLeeGML**
Migration of fieldservice_maintenance to 13.0

#354 

Depends on commit [8e5a34e](https://github.com/OCA/field-service/commits/8e5a34e1fd1b1317b723ae6ddd74e727d7b98f85) -- commit made to 12.0 after migration of fieldservice to 13.0

### CODE REVIEW

**Comment by dreispt** [comment]
@RLeeOSI is something missing to get the build green?
Has the missing v12 commit being added here?

**Comment by brian10048** [comment]
@dreispt 
> Has the missing v12 commit being added here?

The commit from v12 is added in #655

**Comment by brian10048** [comment]
> 
> 
> @dreispt
> 
> > Has the missing v12 commit being added here?
> 
> The commit from v12 is added in #655

Actually, I have a PR [here](#608 ) that already has the commit needed that should allow this to have a green build

**Comment by RLeeGML** [comment]
@dreispt Build is green except for test coverage

**Comment by brian10048** [comment]
> 
> 
> @dreispt Build is green except for test coverage

Can we review and merge #608 first? And remove those commits from this PR?

**Comment by RLeeGML** [comment]
Closed for #670

**Pull request closed without merging**
