### PR TITLE
[IMP] fieldservice readme

### PR DESCRIPTION
**Pull request by brian10048**
Added some more details to readme

#252

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by kittiu** [comment]
@brian10048 thank you. I will add test on this module first, before continue with the recurring...

**Comment by brian10048** [comment]
@max3903 is there any reason @OCA-git-bot did not update the main readme file in fieldservice folder with these changes?  Anything I did incorrectly?

**Comment by max3903** [comment]
@brian10048 Travis and Runbot are failing so we cannot use @OCA-git-bot on this branch yet. This should be fixed with the new version of the stock_request module and #238

**Comment by sbidoul** [comment]
@brian10048 @max3903 The bot is attempting to generate the readme after merge in any case.
It fails because there are issues with the fragments (mainly with the title underlines).

Can you please run the readme generator manually to check and fix them?

**Comment by max3903** [comment]
@sbidoul How do we do that? Can you point us to some doc please?

**Comment by sbidoul** [comment]
https://github.com/oca/maintainer-tools#readme-generator

**Comment by max3903** [comment]
@sbidoul Thank you. @brian10048 Fixed in #259

**Pull request merged**
