### PR TITLE
[17.0][MIG]  fieldservice_recurring: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 154100

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/field-service/issues/1132

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by mpascuall — APPROVED** [review]
Functionally working, checked in runboat

**Comment by peluko00** [comment]
Hi @max3903, is ready to merge?

**Comment by max3903** [comment]
@peluko00 Yes!

**Pull request merged**
