### PR TITLE
[14.0] [MIG] fieldservice_google_marker_icon_picker

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**
depends on #769

### CODE REVIEW

**Comment by Freni-OSI** [comment]
@max3903 , It's ready for review.

**Review by nikul-serpentcs — APPROVED** [review]
LGTM :+1: 
Ready to merge :rocket: 

@brian10048 @max3903 can you please take a look?

**Review by max3903 — APPROVED** [review]

**Pull request merged**
