### PR TITLE
[ADD] fieldservice_stage_close_date

### PR DESCRIPTION
**Pull request by BojanOD**
Datetime field added to the fsm.order that tells the exact time when an order has been closed.
An order has been closed if the order stage is_closed.

### CODE REVIEW

**Comment by damdam-s** [comment]
Can you please add unit tests on this?

**Comment by brian10048** [comment]
@BojanOD thank you for this addition.  Everything looks good.

I would only suggest a more descriptive module name such as `fieldservice_stage_close_date` and squash commits once completed

**Review by marcos-mendez — APPROVED** [review]
LGTM, Tested under LXC and RB

**Review by dreispt — COMMENTED** [review]
Why not just adding this directly to the `fieldservice` base module?

**Comment by damdam-s** [comment]
reason is to have simple modules and not a big `fieldservice` one. 
if the PSC thinks it's better to incorporate this one to the main one, no issue.
We did the "split" for modularity reasons and not to have this behaviour mandatory

**Comment by dreispt** [comment]
That is true, but OTOH a module should provide a reasonably feature set.
No strong opinion myself on this.

**Pull request closed without merging**
