### PR TITLE
[13.0] fieldservice: add fsm_location as contact type

### PR DESCRIPTION
**Pull request by hparfr**
allow to create fsm_location like invoice or delivery addresses
Screenshot_2021-01-18 Akretion - Odoo

### CODE REVIEW

**Comment by hparfr** [comment]
@brian10048 @max3903 @osi-scampbell 
Can I have you review  on this one ?

**Comment by hparfr** [comment]
ping @mourad-ehm

**Review by mourad-ehm — APPROVED** [review]

**Comment by brian10048** [comment]
@hparfr I am receiving an error when testing on runbot.

**Steps to Reproduce:**
Create or select a Contact
Edit the contact and click Add to add a new child partner
Select Location as the type and add the child partner details
Save the Parent partner
Receive error

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1327, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/.repo_requirements/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 67, in write
    res = super(ResPartner, self).write(value)
  File "/.repo_requirements/odoo/addons/snailmail/models/res_partner.py", line 24, in write
    return super(ResPartner, self).write(vals)
  File "/.repo_requirements/odoo/addons/partner_autocomplete/models/res_partner.py", line 197, in write
    res = super(ResPartner, self).write(values)
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 528, in write
    result = result and super(Partner, self).write(vals)
  File "/.repo_requirements/odoo/addons/mail/models/mail_activity.py", line 726, in write
    return super(MailActivityMixin, self).write(vals)
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/.repo_requirements/odoo/odoo/models.py", line 3610, in write
    field.write(self, vals[fname])
  File "/.repo_requirements/odoo/odoo/fields.py", line 2902, in write
    return self.write_batch([(records, value)])
  File "/.repo_requirements/odoo/odoo/fields.py", line 2923, in write_batch
    return self.write_real(records_commands_list, create)
  File "/.repo_requirements/odoo/odoo/fields.py", line 3096, in write_real
    flush()
  File "/.repo_requirements/odoo/odoo/fields.py", line 3060, in flush
    comodel.create(to_create)
  File "<decorator-gen-122>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/addons/partner_autocomplete/models/res_partner.py", line 183, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-81>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 550, in create
    partner._fields_sync(vals)
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 444, in _fields_sync
    self._commercial_sync_from_company()
  File "/.repo_requirements/odoo/odoo/addons/base/models/res_partner.py", line 424, in _commercial_sync_from_company
    self.write(sync_vals)
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 69, in write
    self._convert_fsm_location()
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 62, in _convert_fsm_location
    wiz.action_convert_location(synced)
  File "/home/odoo/build/OCA/field-service/fieldservice/wizard/fsm_wizard.py", line 37, in action_convert_location
    self.env["fsm.location"].create(vals)
  File "<decorator-gen-134>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/home/odoo/build/OCA/field-service/fieldservice_geoengine/models/fsm_location.py", line 16, in create
    res = super(FSMLocation, self).create(vals)
  File "<decorator-gen-108>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 269, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3799, in create
    parent.write(data['inherited'][model_name])
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 69, in write
    self._convert_fsm_location()
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 62, in _convert_fsm_location
    wiz.action_convert_location(synced)
  File "/home/odoo/build/OCA/field-service/fieldservice/wizard/fsm_wizard.py", line 37, in action_convert_location
    self.env["fsm.location"].create(vals)
  File "<decorator-gen-134>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/home/odoo/build/OCA/field-service/fieldservice_geoengine/models/fsm_location.py", line 16, in create
    res = super(FSMLocation, self).create(vals)
  File "<decorator-gen-108>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 269, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3799, in create
    parent.write(data['inherited'][model_name])
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 69, in write
    self._convert_fsm_location()
  File "/home/odoo/build/OCA/field-service/fieldservice/models/res_partner.py", line 62, in _convert_fsm_location
    wiz.action_convert_location(synced)
  File "/home/odoo/build/OCA/field-service/fieldservice/wizard/fsm_wizard.py", line 37, in action_convert_location
    self.env["fsm.location"].create(vals)
  File "<decorator-gen-134>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 314, in _model_create_single
    return create(self, arg)
  File "/home/odoo/build/OCA/field-service/fieldservice_geoengine/models/fsm_location.py", line 16, in create
    res = super(FSMLocation, self).create(vals)
  File "<decorator-gen-108>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 335, in _model_create_multi
    return create(self, [arg])
  File "/.repo_requirements/odoo/addons/mail/models/mail_thread.py", line 269, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/.repo_requirements/odoo/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/.repo_requirements/odoo/odoo/models.py", line 3754, in create
    vals = self._add_missing_default_values(vals)
  File "/.repo_requirements/odoo/odoo/models.py", line 1792, in _add_missing_default_values
    defaults = self.default_get(list(missing_defaults))
  File "/.repo_requirements/odoo/odoo/models.py", line 1244, in default_get
    defaults[name] = field.default(self)
  File "/home/odoo/build/OCA/field-service/fieldservice/models/fsm_location.py", line 80, in <lambda>
    default=lambda self: self._default_stage_id(),
  File "/home/odoo/build/OCA/field-service/fieldservice/models/fsm_location.py", line 134, in _default_stage_id
    [("stage_type", "=", "location"), ("sequence", "=", "1")]
  File "/.repo_requirements/odoo/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4480, in _search
    self._apply_ir_rules(query, 'read')
  File "/.repo_requirements/odoo/odoo/models.py", line 4260, in _apply_ir_rules
    where_clause, where_params, tables = Rule.domain_get(self._name, mode)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_rule.py", line 188, in domain_get
    query = self.env[model_name].sudo()._where_calc(dom, active_test=False)
  File "/.repo_requirements/odoo/odoo/models.py", line 4199, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 1046, in parse
    dom = HIERARCHY_FUNCS[operator](left, ids2, comodel, prefix=field.comodel_name)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 771, in child_of_domain
    ids = left_model.search([(parent_name, 'in', ids)], order='id').ids
  File "/.repo_requirements/odoo/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4470, in _search
    model.check_access_rights('read')
  File "/.repo_requirements/odoo/odoo/models.py", line 3264, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-22>", line 2, in check
  File "/.repo_requirements/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 45, in __getitem__
    self[a[0]] = a[1]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/tools/lru.py", line 51, in __setitem__
    del self[obj]
  File "/.repo_requirements/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by hparfr** [comment]
Replaced by #748 for v14.

**Pull request closed without merging**
