### PR TITLE
[14.0][FIX] fieldservice (You are not allowed to access 'Action Window' (ir.actions.act_window) records)

### PR DESCRIPTION
**Pull request by murtuzasaleh**
You are not allowed to access 'Action Window' (ir.actions.act_window) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary.

### CODE REVIEW

**Comment by smangukiya** [comment]
@murtuzasaleh Would you please increase code coverage? Thanks

**Review by smangukiya — APPROVED** [review]
Except code coverage, fix looks good.

**Comment by AmmarOfficewalaSerpentCS** [comment]
@smangukiya, 
Except code coverage is good now.

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
