### PR TITLE
[12.0][IMP] fieldservice_agreement, add unit test

### PR DESCRIPTION
**Pull request by kittiu**
Done  with the test script, with some remarks as follows.

### CODE REVIEW

**Comment by kittiu** [comment]
Test will error by this line,
https://github.com/OCA/field-service/blob/12.0/fieldservice_agreement/models/fsm_person.py#L20-L21
https://github.com/OCA/field-service/blob/12.0/fieldservice_agreement/models/fsm_person.py#L26-L27
The external id will has space when ref() in code

**Comment by kittiu** [comment]
I also have question about following code, while it works but should we 1) Use for loop 2) Use [('partner_id.name', '=', self.name)]

https://github.com/OCA/field-service/blob/12.0/fieldservice_agreement/models/fsm_person.py#L13-L15

**Comment by kittiu** [comment]
I also have question, looking into the code in **fsm_person.py**, it looks like the field `partner_id` in agreement should be **Worker** and not Customer ?

Just wonder, but no objection.

**Comment by max3903** [comment]
@kittiu The agreement is linked to `partner_id` to apply to customer, vendor and worker.

**Comment by kittiu** [comment]
@max3903 let me know if this PR need any changes.

**Review by max3903 — APPROVED** [review]

**Review by osi-scampbell — APPROVED** [review]

**Pull request merged**
