### PR TITLE
[13.0] [MIG] fieldservice_geoengine

### PR DESCRIPTION
**Pull request by JevinD**
Fieldservice_geoengine migration from 12.0 to 13.0

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
Functional reviewed. :+1:

**Review by brian10048 — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Comment by brian10048** [comment]
@dreispt Travis is hung up during the merge https://travis-ci.org/github/OCA/field-service/jobs/738114705  Not sure what the proper protocol is to fix

**Comment by bodedra** [comment]
@OCA/field-service-maintainers Would you please help us on this.

**Pull request merged**
