### PR TITLE
[FIX] fieldservice_stock_request: remove route_ids fields from requests

### PR DESCRIPTION
**Pull request by tafaRU**
This is due after merge of https://github.com/OCA/stock-logistics-warehouse/pull/2179
Ortherwise the module upgrade raises a ValidationError while validating view.

I paste below the tracebak error (sorry if it's in *italian*):

```
Il campo "route_ids" non esiste nel modello "stock.request"

View name: fsm.order.form.stock.request
Error context:
 view: ir.ui.view(1684,)
 xmlid: view_fsm_order_form_inherit_stock_request
 view.model: fsm.order
 view.parent: ir.ui.view(1614,)
 file: /srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/addons/fieldservice_stock_request/views/fsm_order.xml


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /srv/odoo/.pyenv/versions/3.8.13/lib/python3.8/site-packages/odoo/addons/fieldservice_stock_request/views/fsm_order.xml:2, near
<record id="view_fsm_order_form_inherit_stock_request" model="ir.ui.view">
        <field name="name">fsm.order.form.stock.request</field>
        <field name="model">fsm.order</field>
        <field name="inherit_id" ref="fieldservice_stock.view_fsm_order_form_inherit_stock"/>
        <field name="arch" type="xml">
            <data><xpath expr="//notebook/page[@id='stock']" position="inside">
                <header>
                    <button name="action_request_submit" attrs="{'invisible': [('request_stage', 'not in', ['draft'])]}" type="object" class="oe_highlight" string="Submit"/>
                    <button name="action_request_draft" type="object" attrs="{'invisible': [('request_stage', 'not in', ['cancel'])]}" class="oe_highlight" string="Set to Draft"/>
                    <button name="action_request_cancel" attrs="{'invisible': [('request_stage', 'not in', ['draft','submitted','open'])]}" type="object" string="Cancel"/>
                    <field name="request_stage" widget="statusbar"/>
                </header>
            </xpath>
            <field name="move_ids" position="before">
                <field name="stock_request_ids" nolabel="1">
                    <tree editable="bottom">
                        <field name="name" readonly="1"/>
                        <field name="product_id"/>
                        <field name="order_id" force_save="1"/>
                        <field name="allowed_uom_categ_id" invisible="1"/>
                        <field name="allow_virtual_location" invisible="1"/>
                        <field name="product_uom_id" options="{'no_open': True, 'no_create': True}" groups="uom.group_uom"/>
                        <field name="direction" required="1"/>
                        <field name="route_id" options="{'no_create': True}" groups="stock.group_stock_multi_locations" invisible="1"/>
                        <field name="route_ids" invisible="1"/>
                        <field name="product_uom_qty"/>
                        <field name="qty_in_progress"/>
                        <field name="qty_done"/>
                        <field name="expected_date"/>
                        <field name="picking_policy" invisible="1"/>
                        <field name="warehouse_id" invisible="1"/>
                        <field name="location_id" invisible="0"/>
                        <field name="procurement_group_id" invisible="1"/>
                        <field name="company_id" invisible="1"/>
                        <field name="state"/>
                    </tree>
                </field>
            </field>
        </data></field>
    </record>
```

### CODE REVIEW

**Comment by tafaRU** [comment]
The [error](https://github.com/OCA/field-service/actions/runs/11795689952/job/32855936052?pr=1260#step:8:185) with OCB build seems unrelated with this change. Please let me know if you have some hints in order to fix it.

@OCA/field-service-maintainers note that this is a hot fix so please review it asap. Thank you in advance.

**Comment by max3903** [comment]
@tafaRU Sounds like https://github.com/OCA/stock-logistics-warehouse/pull/2179 has been merged a little too quickly.

**Review by max3903 — APPROVED** [review]

**Comment by tafaRU** [comment]
thank you @max3903!

**Comment by tafaRU** [comment]
ah wait! Bot evidently failed due to https://github.com/OCA/field-service/pull/1260#issuecomment-2470219369:

> The [error](https://github.com/OCA/field-service/actions/runs/11795689952/job/32855936052?pr=1260#step:8:185) with OCB build seems unrelated with this change. Please let me know if you have some hints in order to fix it.

**Comment by max3903** [comment]
@tafaRU Can you fix it? I believe we should have a decimal accuracy for coordinates evaluation and avoid those problems.

**Comment by tafaRU** [comment]
> I believe we should have a decimal accuracy for coordinates evaluation

Do you mean something different to: https://github.com/OCA/field-service/blob/e7261e007f9e809fe11c28cf0a1628a75280da87/fieldservice_geoengine/tests/test_fsm_location.py#L21 ?

> Can you fix it?

I think I don't know the subject well enough.
Just looking at the error raised a quick solution should be:

* modify the following value:
https://github.com/OCA/field-service/blob/e7261e007f9e809fe11c28cf0a1628a75280da87/fieldservice_geoengine/tests/test_fsm_location.py#L63

* or modify `delta` value.

But I would prefer to hear your (@max3903) opinion and @wolfhall's opinion first.

**Comment by max3903** [comment]
@tafaRU https://github.com/OCA/field-service/pull/1261

**Comment by tafaRU** [comment]
@max3903 the two PRs need to be joined otherwise tests still failed. Considering that I saw how you want to solve the problem, I can apply the same change here.

**Comment by tafaRU** [comment]
@max3903 I tried with https://github.com/OCA/field-service/pull/1261/files#diff-5bb01fb053f7854ebc88cedfc762dd2f1704affa9c3e391632ad7d7a7278abbbR63 but it doesn't work :thinking:

**Comment by tafaRU** [comment]
Also note the two builds get different errors:

* OCB: https://github.com/OCA/field-service/actions/runs/11795689952/job/32855936052?pr=1260#step:8:185
* Odoo: https://github.com/OCA/field-service/actions/runs/11842077879/job/32999853022?pr=1260#step:8:186

**Comment by tafaRU** [comment]
@max3903 seeing https://github.com/OCA/field-service/pull/1261 was :green_circle: I tried to drop the last commit and I don't know exactly why but it works!
If it's not a problem I'd prefer merging this. Thanks!

**Comment by max3903** [comment]
@tafaRU FYI https://github.com/OCA/stock-logistics-warehouse/pull/2198

**Comment by tafaRU** [comment]
Ok thanks for sharing, I close this then.

**Pull request closed without merging**
