### PR TITLE
[IMP] fieldservice_sale_recurring: Add test

### PR DESCRIPTION
**Pull request by brian10048**
Depends on #486

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
:+1:

**Review by dreispt — APPROVED** [review]
Tests should not depend on demo data, they should build their test data.
This allows them to be used on non demo databases, such as a test copy of production.
Still, while not perfect, this is better than no tests at all...

**Comment by brian10048** [comment]
Thanks @dreispt . That is good to know for the future.

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
