### PR TITLE
[12.0][IMP] fieldservice_maintenance: add scheduled_date_start and scheduled_duration from maintenance request

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Adds the scheduled_date_start and scheduled_duration to the FSM Order created via the Maintenance Order.

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @OCA/field-service-maintainers Does anyone know why an error is occurring in the runbot?

**Comment by rvalyi** [comment]
> ping @OCA/field-service-maintainers Does anyone know why an error is occurring in the runbot?

Runbot had an error when trying to access the "full logs", so I just restarted it. Let's see...

**Comment by rvalyi** [comment]
Really it seems there is a problem with Runbot and the field-service repo. Even 20 min after you launched the Runbot, if you try to access the full logs, for instance with https://runbot.odoo-community.org/runbot/build/3487949
you get this error:
```
Unable to find image 'oca-field-service:f85b710_env_2_job_1' locally
docker: Error response from daemon: pull access denied for oca-field-service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
(I got that same error in the 1st original build from @marcelsavegnago and not 20 min ago).

cc @gurneyalex any clue?

**Comment by marcelsavegnago** [comment]
ping @OCA/field-service-maintainers

**Comment by marcelsavegnago** [comment]
ping @OCA/field-service-maintainers 
```
Unable to find image 'oca-field-service:f85b710_env_2_job_1' locally
docker: Error response from daemon: pull access denied for oca-field-service, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by marcelsavegnago** [comment]
@rvalyi after 1 year I did a rebase :D

**Pull request merged**
