### PR TITLE
[12.0][ADD] fieldservice_route_vehicle

### PR DESCRIPTION
**Pull request by murtuzasaleh**
#390 

Depends on:
- [x] #432

### CODE REVIEW

**Comment by dreispt** [comment]
@murtuzasaleh Please include in the description the link to the design being implemented. In this case #390

**Comment by murtuzasaleh** [comment]
@max3903 @dreispt Can you please review this PR.

**Comment by max3903** [comment]
@murtuzasaleh This looks good, but let's merge #432 first.

**Review by max3903 — APPROVED** [review]

**Review by nelsonramirezs — APPROVED** [review]

**Pull request merged**
