### PR TITLE
[IMP] fieldservice_sale

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by brian10048 — APPROVED** [review]

**Comment by murtuzasaleh** [comment]
@max3903  Got error when I created Product and configured << Sale <<  (Field Service Tracking | Create one FSM order per sale order) and Created Sale order based on that and confirm it.

Sale

**Comment by murtuzasaleh** [comment]
> @max3903 Got error when I created Product and configured << Sale << (Field Service Tracking | Create one FSM order per sale order) and Created Sale order based on that and confirm it.
> 
> Sale

The issue is because of **Service Location** field is not **required** in the **Sale order** and it is **required** in **FSM Order**

**Comment by brian10048** [comment]
> 
> 
> > @max3903 Got error when I created Product and configured << Sale << (Field Service Tracking | Create one FSM order per sale order) and Created Sale order based on that and confirm it.
> > Sale
> 
> The issue is because of **Service Location** field is not **required** in the **Sale order** and it is **required** in **FSM Order**

How about raising a Validation Error if the sale order FSM location is empty and any sale order lines are set to any of the field service tracking options

**Comment by max3903** [comment]
> How about raising a Validation Error if the sale order FSM location is empty and any sale order lines are set to any of the field service tracking options

:+1:

**Comment by brian10048** [comment]
@max3903 please review [https://github.com/ursais/field-service/pull/22](https://github.com/ursais/field-service/pull/22)

I added the validation error and did some bug fixes

**Review by bodedra — APPROVED** [review]
Code review. LGTM :+1:

**Review by murtuzasaleh — APPROVED** [review]

**Comment by murtuzasaleh** [comment]
#461

**Pull request merged**
