### PR TITLE
[12.0][FIX] fieldservice Remove required attribute from view

### PR DESCRIPTION
**Pull request by hparfr**
I think this field shouldn't be required.

### CODE REVIEW

**Comment by brian10048** [comment]
I agree.  LGTM.
@max3903 is there any reason your team would need this to be a required field?

**Comment by max3903** [comment]
Not that I remember...

**Review by max3903 — APPROVED** [review]

**Review by brian10048 — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]

**Comment by max3903** [comment]
@hparfr Can you bump the version number please?

**Comment by hparfr** [comment]
@max3903 done

**Review by bodedra — APPROVED** [review]

**Pull request merged**
