### PR TITLE
[14.0] [mig] fieldservice_stock

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by Freni-OSI** [comment]
Needs review.
CC: @patrickrwilson

**Comment by patrickrwilson** [comment]
@Freni-OSI can you squash all the automated commits? (translations, .pot, readme updates)

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by osi-scampbell — APPROVED** [review]

**Review by smangukiya — APPROVED** [review]
Code looks good.

**Pull request merged**
