### PR TITLE
[12.0][ADD] fieldservice_agreement_helpdesk_mgmt

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This module links Field Service, Agreements and Help Desk together by setting the agreement fields when creating Field Service orders from a ticket.

Depends https://github.com/OCA/contract/pull/529

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @brian10048 @bodedra @dalonsod

**Review by dalonsod — CHANGES_REQUESTED** [review]
Only code review, maybe a test should be added

**Comment by marcelsavegnago** [comment]
> Only code review, maybe a test should be added

Done

**Review by jpcarassato — APPROVED** [review]
Ok

**Comment by marcelsavegnago** [comment]
ping @dalonsod

**Review by dalonsod — APPROVED** [review]
Tested on runbot :+1:

**Comment by marcelsavegnago** [comment]
ping @bodedra @brian10048

**Review by bodedra — APPROVED** [review]
Functional review :+1:

**Comment by marcelsavegnago** [comment]
@OCA/field-service-maintainers can merge this PR?

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
