### PR TITLE
[14.0][MIG] fieldservice_equipment_stock

### PR DESCRIPTION
**Pull request by ReedHayashikawa**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@ReedHayashikawa can you please check Travis.

**Comment by Freni-OSI** [comment]
cc: @patrickrwilson

**Review by patrickrwilson — APPROVED** [review]
Works and looks good. LGTM

**Review by osi-scampbell — APPROVED** [review]

**Comment by osi-scampbell** [comment]
@ReedHayashikawa Can you confirm your test cases are covering all the python methods? We are still missing one of the checks here on code coverage

**Review by smangukiya — APPROVED** [review]

**Pull request merged**
