### PR TITLE
[17.0][MIG] fieldservice_equipment_stock: Migration to 17.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Review by imlopes — APPROVED** [review]

**Comment by imlopes** [comment]
@max3903 Do you know if it's possible to have this PR merged ?
Thanks

**Review by dreispt — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by yankinmax** [comment]
Thanks @imlopes for finishing this PR

**Pull request merged**
