### PR TITLE
[14.0][MIG]fieldservice_account

### PR DESCRIPTION
**Pull request by Freni-OSI**
[14.0][MIG]Migrated fieldservice_account from v13 to v14.

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Code review. LGTM

**Review by brian10048 — CHANGES_REQUESTED** [review]
Thank you @Freni-OSI 
I do not think we should be updating the directory for the migration files from 13.* to 14.*

I believe they should be kept with the same directory or removed completely if we do not need them in v14.

cc: @hparfr - do you have any thoughts on this?

**Comment by hparfr** [comment]
>Remove any possible migration script from previous version. 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

You can also use https://github.com/OCA/odoo-module-migrator to help you with this.

**Comment by fshah-initos** [comment]
Hi @Freni-OSI can you please have a look at above comments?

**Comment by fshah-initos** [comment]
Hi @Freni-OSI It wiuld be nice if you can have a look at the comments and do the needfull so that we can get this PR merge soon.

**Comment by fshah-initos** [comment]
It would be great if we could merge the PR.

**Comment by fshah-initos** [comment]
It would be great if we could merge the PR.

**Comment by fshah-initos** [comment]
@OCA/field-service-maintainers can you please merge this?

**Review by brian10048 — APPROVED** [review]

**Pull request merged**
