### PR TITLE
[FIX] order geo view

### PR DESCRIPTION
**Pull request by brian10048**
@max3903, this is in reference to an error @jesulo reported in #82

### CODE REVIEW

**Review by bodedra — APPROVED** [review]
Reasonable :+1:

**Comment by jesulo** [comment]
Thanks! @brian10048

**Comment by smangukiya** [comment]
@max3903/ @brian10048  : If you take a look at PR https://github.com/OCA/field-service/pull/59. I have mention it  it would work accurately once we merge related https://github.com/asaunier/geospatial/pull/1 

By doing that, this error/issue will no longer be there. As it was developed using that base_geoengine module

I hope this will helps. Thanks

**Comment by brian10048** [comment]
@smangukiya OK, I see what's going on now.  It looks like what we really need is the 11.0 base_geoengine module to be finished and merged into the OCA so we are all using the same one.  In #86 @jesulo is having another issue which I am assuming is related to using a different base_geoengine module.

**Comment by wolfhall** [comment]
@brian10048 - I reached out to CampToCamp to push the GeoEngine V11.0 base_geoengine release out.  Hopefully, they can do this soon. 
@yvaucher

**Comment by max3903** [comment]
https://github.com/OCA/geospatial/pull/178

**Pull request closed without merging**
