### PR TITLE
[14.0][MIG]fieldservice_vehicle: Migrated from v13 to v14.

### PR DESCRIPTION
**Pull request by Chanakya-OSI**

### CODE REVIEW

**Comment by brian10048** [comment]
Hello @Chanakya-OSI
This should be ready to migrate now as base fieldservice v14 is merged.  

Please see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch for instructions.  It is important to use the `git format-patch` command to keep the previous commit history for this module

**Comment by smangukiya** [comment]
@Freni-OSI Can you please increase code coverage to 90%? Rest is good. Thanks

**Comment by Freni-OSI** [comment]
Needs Review.
CC: @patrickrwilson @smangukiya

**Review by patrickrwilson — APPROVED** [review]
Tested and works, code looks good to me. LGTM

**Pull request merged**
