### PR TITLE
[14.0][MIG] fieldservice_agreement (Version 12.0 to 14.0)

### PR DESCRIPTION
**Pull request by patrickrwilson**
Depends on https://github.com/OCA/contract/pull/671 and https://github.com/OCA/contract/pull/666

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@osi-scampbell @ReedHayashikawa can you assist with review?

**Review by osi-scampbell — APPROVED** [review]
@patrickrwilson  This PR looks good, let's change the headers on the .py files toi 2021. Also, can you add yourself to the Contributors.rst file and list yourself as a maintainer in the __manifest__.py file.

**Comment by patrickrwilson** [comment]
> This PR looks good, let's change the headers on the .py files toi 2021. Also, can you add yourself to the Contributors.rst file and list yourself as a maintainer in the **manifest**.py file.

@osi-scampbell I've added myself in maintainer list however for the date I think for OCA they maintain the original dates in those headers.

**Review by smangukiya — APPROVED** [review]

**Pull request merged**
