### PR TITLE
[17.0][MIG] fieldservice_vehicle: Migration to 17.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0 

cc https://github.com/APSL 154106

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/field-service/issues/1132

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by peluko00** [comment]
Ready to merge @max3903 ?

**Comment by max3903** [comment]
@peluko00 Sure!

**Pull request merged**
