### PR TITLE
[IMP][12.0] Fixed issued of a field service timeline view with a diffren object timeline view conflict.

### LINKED ISSUE #379: Time line
after instalation of the Field service module in Odoo 12 the Project time line stopped working with the error: (the timeline of Field service working though) 
Uncaught TypeError: Cannot read property '_fieldId' of null
https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:35
Traceback:
TypeError: Cannot read property '_fieldId' of null
    at n._onAddItem (https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:35:20602)
    at Array.s (https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:28:12634)
    at Object.emit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:129439)
    at lt.emit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:127478)
    at lt.tryEmit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:123217)
    at lt.recognize (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:123547)
    at Object.recognize (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:128441)
    at z.O [as callback] (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:112132)
    at z.handler (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:120058)
    at C.domHandler (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:111825)

How to fix it?

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**

### CODE REVIEW

**Comment by brian10048** [comment]
Thank you @AmmarOfficewalaSerpentCS 

Can you rebase and squash the merge commits to keep the commit history clean?

**Comment by AmmarOfficewalaSerpentCS** [comment]
@brian10048 :- Done 
@smangukiya  :- Please review this PR.

**Comment by brian10048** [comment]
Thank you @AmmarOfficewalaSerpentCS !

**Comment by AmmarOfficewalaSerpentCS** [comment]
@brian10048 :- Can you please help me to green a runbot, what is the issue for a runbot?
I checked a log but I can't found any warning's or error's

**Review by smangukiya — APPROVED** [review]
LGTM. @AmmarOfficewalaSerpentCS : Thank you for your contribution here.

@brian10048 : Were you able to identify the run bot failed case, it looks good to me though.

Thanks

**Comment by brian10048** [comment]
I think runbot was successful but was killed early.    I tested the build yesterday on runbot when it had the extra merge commits and the mentioned bug was fixed

**Review by brian10048 — APPROVED** [review]
/ocabot merge patch

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
