### PR TITLE
[FIX] fieldservice_account: required customer_id no longer breaks installation

### PR DESCRIPTION
**Pull request by dreispt**
Relevant for #367

### CODE REVIEW

**Comment by max3903** [comment]
@dreispt I would keep the field required and have a hook to set the value to the same as the owner by default.

**Comment by brian10048** [comment]
I was thinking it should stay required as well

**Comment by max3903** [comment]
@dreispt FYI
https://github.com/OCA/field-service/pull/367/files#diff-2df1f2c4a8f6d8a31e786e8a3b39bc72R16

**Comment by dreispt** [comment]
A required field imposes something to all use cases, so you should make sure you have a strong reason to do so.
I think there are valid scenarios where we don't need a Location Customer, and even think it would be useful to have the customer invoicing features disabled for those cases.

So I still think we will have a better solution keeping this field optional.

**Pull request closed without merging**
