### PR TITLE
[17.0][MIG] fieldservice_stock_request: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 156932
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/field-service/issues/1132

Depends on:
- [stock_request_picking_type] https://github.com/OCA/stock-logistics-request/pull/34
- [stock_request_submit] https://github.com/OCA/stock-logistics-request/pull/24

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM

**Review by lbarry-apsl — APPROVED** [review]
I see it well

**Comment by peluko00** [comment]
It's ready for merge @max3903

**Pull request merged**
