### PR TITLE
[ADD] Vehicle

### PR DESCRIPTION
**Pull request by brian10048**
Is this what is needed for #4 ?

Still need to add some reporting features

### CODE REVIEW

**Comment by max3903** [comment]
Thanks @brian10048. Nice work!

Let me know if you need help signing the CLA and fixing Travis errors.

**Comment by brian10048** [comment]
Glad to be a part @max3903 

I emailed my signed CLA with GitHub login yesterday once the comment was posted here. 

Looks like Travis errors are good now as well!

**Comment by max3903** [comment]
@brian10048 I processed your CLA. :+1:

**Comment by etobella** [comment]
I am probably late, but why are you adding vehicles on the main module? IMHO, it should be made modular. So if a company has vehicles, it should be added as a new module. If all is added on the same module, you may have all functionality but in some cases only 30% is used

**Comment by max3903** [comment]
The future module `fieldservice_vehicle` is meant to depend on `fleet` to extend the fsm.vehicle with fleet features.

The idea is to provide the basic features with settings in a single module, and advanced ones with additional modules.

**Comment by etobella** [comment]
Vehicles should not be a basic feature. On your documents, you expected to add features for even doctors, but they usually don't use  vehicles. I think the main module should have the service order and all the shared models. All the other models should be added on new modules.
If you add all the functionalities on the initial module, it is harder to use it, and some possible may loose the interest on it.

**Comment by max3903** [comment]
Vehicle feature is only visible if you activate it in the settings, like invoicing vs accounting or product template vs variants.

**Comment by brian10048** [comment]
The vehicle features are hidden by default in the core module and require
no additional dependencies

The nature of field service would most of the time require that you use a
vehicle to travel to the location being serviced. If one doesn't need to
track vehicle data, the feature can remain off.

**Comment by etobella** [comment]
Yes, I know, but you are adding unnecessary features on the initial module. That is what i mean.
For example, when bank-payment was created, all could be added on a single module, but it was splitted in order to not include too much functionality on a single module. I think it is the best approach, but it is just my opinion.

**Pull request merged**
