### PR TITLE
[14.0][MIG] fieldservice_stock_request

### PR DESCRIPTION
**Pull request by Vimal-OSI**
Dependency:

- [x] https://github.com/OCA/stock-logistics-warehouse/pull/1223

### CODE REVIEW

**Comment by vimalpatelserpentcs** [comment]
> Dependency:
> 
> * [x]  [[14.0][MIG] stock_request_direction stock-logistics-warehouse#1126](https://github.com/OCA/stock-logistics-warehouse/pull/1126)

- [x] https://github.com/OCA/stock-logistics-warehouse/pull/1223

**Comment by aymenrahmay** [comment]
Is the update regarding  the migration of this module to the 14 version

**Comment by castalie-dev** [comment]
is there any updates regarding the migration of this module ?

**Comment by TheCloneMaster** [comment]
HI, is this only waiting for stock_request_direction approval into 14.0 ?

**Comment by TheCloneMaster** [comment]
Hi @dreispt, @brian10048, 

The module stock_request_direction has already been approved, could you please merge this one too?

Regards

**Comment by max3903** [comment]
@Vimal-OSI Can you fix the errors?

**Comment by nikul-serpentcs** [comment]
Hello @max3903 @brian10048 **Mr.Travis** is happy :smile:  
Ready to merge :rocket: 

Can you please take a look?

**Review by max3903 — APPROVED** [review]

**Pull request merged**
