### PR TITLE
[14.0][FIX] fieldservice_*: adapt access to ir.actions.* records

### LINKED ISSUE #915: [14.0] fieldservice: smart buttons not working
## Modules Affected
[x] - fieldservice #916 
[ ] - fieldservice_account
[ ] - fieldservice_account_payment
[ ] - fieldservice_agreement
[ ] - fieldservice_distribution
[ ] - fieldservice_isp_account
[x] - fieldservice_partner_multi_relation #917 
[x] - fieldservice_project #918 
[ ] - fieldservice_purchase
[ ] - fieldservice_sale
[ ] - fieldservice_stock

## Describe the bug
most Smart buttons are not working. getting error:
```
Access Error
×
You are not allowed to access 'Action Window' (ir.actions.act_window) records.

This operation is allowed for the following groups:
	- Administration/Settings

Contact your administrator to request access if necessary. 

```
## To Reproduce
**Affected versions**:  14.0

1. go to runbot and set demo user as field service administrator
2. log as demo user go to master data / location or workers
3. click on smart buttons

**Expected behavior**
clicking on smart buttons opens the targeted window

**Additional context**
tested on runbot

### PR DESCRIPTION
**Pull request by brian10048**
Fixes #915

### CODE REVIEW

**Comment by ygol** [comment]
@brian10048 is the runboat in pending status because the failed codecov/patch test? should this be fixed 1st?

**Review by ygol — APPROVED** [review]
LGTM beside the runboat in pending status probably because the failed codecov/patch test. Tested functionally in local instance

**Review by hparfr — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
