### PR TITLE
[14.0][FIX] fieldservice_timeline

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**
Removed an unused table inherit.

TypeError: Cannot create a consistent method resolution
order (MRO) for bases BaseModel, mail.thread, mail.activity.mixin, mail.thread.blacklist, base

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@smangukiya , @murtuzasaleh ,
Please review this PR

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt , 
Can you please review this PR ?

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by bodedra — APPROVED** [review]

**Pull request merged**
