### PR TITLE
[15.0][FIX] fieldservice: FSM Category parent

### PR DESCRIPTION
**Pull request by brian10048**
This PR aims to improve the parent/child features of FSM Category.  

- Added decorator to `_compute_full_name` method for dependent fields
- Added keys and fields required to optimize searching and reading categories
- Prevent recursive FSM Categories

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by evsamb15** [comment]
Hi!

After git pull the repository, I'm still getting this error:

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1306, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1325, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/odoo/odoo-server/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/models.py", line 5027, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/models.py", line 1811, in search
    return res if count else self.browse(res)
  File "/odoo/odoo-server/odoo/models.py", line 5159, in browse
    if not ids:
  File "/odoo/odoo-server/odoo/osv/query.py", line 215, in __bool__
    return bool(self._result)
  File "/odoo/odoo-server/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/odoo/odoo-server/odoo/osv/query.py", line 208, in _result
    self._cr.execute(query_str, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/odoo/odoo-server/odoo/sql_db.py", line 89, in check
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 310, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedColumn: column fsm_category.full_name does not exist
LINE 1: ...R ("fsm_category"."company_id" in (1))) ORDER BY  "fsm_categ...
                                                             ^

**Comment by ghost** [comment]
Did you updated the module afterwards?

**Comment by evsamb15** [comment]
I actually didn’t, I did everything but that step, let me do it the be back with the feedback. 
Thanks. 

Emmanuel Vasquez, CEO. 
Cogency Group, LLC & SRL & Ltd. 

Cell: +1 (849)-353-7793
eMail: ***@***.***
Site: www.CogencyG.com

——————————————-
Please note that this msg has been sent on the go.

**Pull request merged**
