### PR TITLE
[16.0][MIG] fieldservice_stock

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
Lgtm

**Comment by yankinmax** [comment]
@gbrito-erpopen can you pls take a look at such issue happening on the build of the repo?
`ERROR odoo odoo.schema: Table 'fsm_location': unable to set NOT NULL on column 'inventory_location_id'`
Probably it worth it to add required attribute on the view.

**Comment by ghost** [comment]
@yankinmax I fixed that issue on this PR https://github.com/OCA/field-service/pull/1002. Let me know if it worked :)

**Pull request merged**
