### PR TITLE
[FIX][12.0] fieldservice_geoengine

### PR DESCRIPTION
**Pull request by murtuzasaleh**
#196

### CODE REVIEW

**Comment by murtuzasaleh** [comment]
@max3903 I need your help in [field_fsm_order_shape](https://github.com/OCA/field-service/pull/198/commits/92462723bf27a035f4a87348faa799cf3f6d3424#diff-22ce73c8ed1ac6e936a86d492a075c7dR63) this field, where can I found this field? I checked in V11 branch code but can't found it.

**Comment by murtuzasaleh** [comment]
@max3903 Can you please check this [comment](https://github.com/OCA/field-service/pull/198#issuecomment-486263740) so we can complete this issue.

**Comment by max3903** [comment]
https://github.com/OCA/field-service/blob/11.0/fieldservice/models/fsm_order.py#L135

**Comment by murtuzasaleh** [comment]
@osi-scampbell @max3903 Can you please review this PR.

**Review by osi-scampbell — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Pull request merged**
