### PR TITLE
[15.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by etobella**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

### CODE REVIEW

**Comment by etobella** [comment]
@sbidoul Something weird is happening here, we launch the merge patch and automatically the bot says that it failed. Any idea why this could happen?

**Comment by sbidoul** [comment]
Looks like .github/workflows/pre-commit.yml has a merge conflict

**Pull request merged**
