### PR TITLE
[MIG] [13.0] fieldservice_stock: Migrate to 13.0

### PR DESCRIPTION
**Pull request by brian10048**
Replaces #671 with most recent changes from v12

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
Good work. I have no suggested changes. LGTM

**Review by marcelsavegnago — APPROVED** [review]
LGTM. Please check runbot error.

**Review by smangukiya — APPROVED** [review]
LGTM

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
runbot was already red before. The code looks good.

/ocabot merge nobump

**Pull request merged**
