### PR TITLE
[12.0][IMP] fieldservice: Remove route

### PR DESCRIPTION
**Pull request by murtuzasaleh**
Removed fsm.route object from here.

Related to #432

### CODE REVIEW

**Comment by murtuzasaleh** [comment]
@max3903 @dreispt Can you please review this PR.

**Comment by dreispt** [comment]
If this is removed, will it be replaced somewhere?
There should be an explanation of the reasons to remove this, for future reference.

**Comment by murtuzasaleh** [comment]
> If this is removed, will it be replaced somewhere?
> There should be an explanation of the reasons to r

fsm.route will be added in fieldservice_route module #380
Cc @max3903

**Comment by murtuzasaleh** [comment]
@max3903 fieldservice_account_analytic and fieldservice_vehicle module have fsm.route model reference.
https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/models/fsm_route.py
https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/views/fsm_route.xml
https://github.com/OCA/field-service/blob/12.0/fieldservice_account_analytic/views/fsm_route.xml

Do we have to add a fieldservice_route module in the dependency?

**Comment by dreispt** [comment]
IMO we should do all the refactoring in the same PR (removing old model, adding new model, changing referencing Models).

I'm aware these modules are in Beta, but is it OK for everyone involved to have this breaking change?

**Comment by brian10048** [comment]
There is almost no route functionality in base field service as it is, so it is fine by me to remove. 

I also think it would make since as one PR with a handful of commits for each major step in the refactoring/addition of routes

**Comment by murtuzasaleh** [comment]
@max3903 @dreispt Can we have to change or update this action? Because it blocks the base flow.
https://github.com/OCA/field-service/blob/12.0/fieldservice/views/fsm_schedule.xml#L28

**Comment by dreispt** [comment]
After Brian’s comment, I’m OK with this PR.
Please get a green build and you’ll have my OK.

**Comment by brian10048** [comment]
> 
> 
> @max3903 fieldservice_account_analytic and fieldservice_vehicle module have fsm.route model reference.
> https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/models/fsm_route.py
> https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/views/fsm_route.xml
> https://github.com/OCA/field-service/blob/12.0/fieldservice_account_analytic/views/fsm_route.xml
> 
> Do we have to add a fieldservice_route module in the dependency?

It looks like you guys are making fieldservice_vehicle_route, so the vehicle related references to routes can go there.

To me it doesn't seem necessary enough to add a dependency to fieldservice_account_analytic just to show the billing_id field in the tree view.

**Comment by max3903** [comment]
> @max3903 fieldservice_account_analytic and fieldservice_vehicle module have fsm.route model reference.
> https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/models/fsm_route.py
> https://github.com/OCA/field-service/blob/12.0/fieldservice_vehicle/views/fsm_route.xml
> https://github.com/OCA/field-service/blob/12.0/fieldservice_account_analytic/views/fsm_route.xml
> 
> Do we have to add a fieldservice_route module in the dependency?

They should not depend on `fieldservice_route`. See #390

**Review by max3903 — APPROVED** [review]

**Review by brian10048 — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Comment by murtuzasaleh** [comment]
> @max3903 @dreispt Can we have to change or update this action? Because it blocks the base flow.
> https://github.com/OCA/field-service/blob/12.0/fieldservice/views/fsm_schedule.xml#L28

@max3903 @dreispt @brian10048  We need these changes functionally?

**Comment by dreispt** [comment]
@murtuzasaleh I just merged this PR. That change, if OK, should go in another PR, sorry.

**Comment by murtuzasaleh** [comment]
> @murtuzasaleh I just merged this PR. That change, if OK, should go in another PR, sorry.

ok

**Pull request merged**
