### PR TITLE
17.0 [MIG] fieldservice_account

### PR DESCRIPTION
**Pull request by SMaciasOSI**
@max3903 @brian10048

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by SMaciasOSI** [comment]
@max3903 @brian10048 This PR fails only the codecov checks. Can we merge?

**Comment by brian10048** [comment]
@SMaciasOSI would you be able to add this commit [1a84c36](https://github.com/OCA/field-service/commit/1a84c369a06f487d1d90853152818f5fc0104f3c) from v14?  It is missing after v14 and would be good to have it here from this point of migration forward
You could squash the two pre-commit commits together.  Looks good otherwise.

**Comment by SMaciasOSI** [comment]
@brian10048 commit added

**Review by brian10048 — APPROVED** [review]

**Pull request merged**
