### PR TITLE
[IMP] fieldservice_stock: Add FSM to Stock Requests, Hide Routes, Only Submit Draft Requests

### PR DESCRIPTION
**Pull request by osi-scampbell**
This PR adds FSM Order to Stock Requests, hides Routes on FSM Orders, and prevents Orders that are finished from being submitted. Only requests in Draft state should be submitted.

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@osi-scampbell Is it still WIP?

**Comment by osi-scampbell** [comment]
@max3903 Can we rerun the travis? If that green lights then we can remove the WIP

**Comment by patrickrwilson** [comment]
During my testing, I created the stock request on an Order, then went into inventory and opened the stock request. 
I can see the transfer was created, so I opened the transfer, click check availability, then validate and got the following error:
File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\stock\wizard\stock_immediate_transfer.py", line 34, in process
    pick_to_do.action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\delivery\models\stock_picking.py", line 106, in action_done
    res = super(StockPicking, self).action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\stock\models\stock_picking.py", line 625, in action_done
    todo_moves._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\purchase_stock\models\stock.py", line 86, in _action_done
    res = super(StockMove, self)._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\fieldservice_stock\models\stock.py", line 67, in _action_done
    res = super(StockMove, rec)._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\stock_account\models\stock.py", line 353, in _action_done
    res = super(StockMove, self)._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\stock\models\stock_move.py", line 1127, in _action_done
    moves_todo.mapped('move_line_ids')._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\helpdesk_stock\models\stock.py", line 19, in _action_done
    res = super(StockMoveLine, self)._action_done()
  File "C:\Program Files (x86)\Odoo 12.0e\server\odoo\addons\fieldservice_stock\models\stock.py", line 47, in _action_done
    if request.state == 'done' and request.fsm_order_id:
AttributeError: 'stock.request.allocation' object has no attribute 'state'

**Comment by osi-scampbell** [comment]
@patrickrwilson @max3903 Sorry about the delay, this commit fixes that error. Looks like we were referencing fields from the wrong model. Also looks like a odoo changed dest_location_id to location_dest_id for v12. When you validate the picking, it should process successfully and show you the tractability report.

**Review by patrickrwilson — APPROVED** [review]
Tested and it's letting me go through till the end so it seems to be working so i'll approve it. 
I do have a question though. It creates a Vehicle Loading record, how does it determine to do that, instead of a delivery order to ship out instead of loading a vehicle?

**Comment by max3903** [comment]
@patrickrwilson It's based on the route.

**Pull request merged**
