### PR TITLE
[15.0][MIG] fieldservice_sale_recurring

### PR DESCRIPTION
**Pull request by Freni-OSI**

### CODE REVIEW

**Comment by max3903** [comment]
@Freni-OSI Please add some unit tests to increase code coverage.

**Comment by Freni-OSI** [comment]
> @Freni-OSI Please add some unit tests to increase code coverage.

@max3903 Done with the UT, Please review it.

**Review by murtuzasaleh — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Pull request merged**
