### PR TITLE
 [16.0][FIX] fieldservice_stock: ensure inventory_location is assigned

### PR DESCRIPTION
**Pull request by ghost**
When install the module, we want to ensure that the existing fsm.location
records have the default inventory_location_id assigned.

### CODE REVIEW

**Comment by max3903** [comment]
@gbrito-erpopen Let's keep the field required in the database and put the default value on the existing data with a hook.

**Comment by ghost** [comment]
I see what you mean, I will add an hook, it will assign the default value on the empty ones.

**Comment by ghost** [comment]
@max3903 I don't think that is the solution. Maybe i'm not seeing correctly but:
 - When the fieldservice_stock is installed, it creates a constrain in the database on the field inventory_location_id.
 - When I run the tests on the fieldservice_account, it tries to create an fsm.location(line 28), but since we are not aware of the fieldservice_stock, we don't add the field inventory_location_id, odoo triggers this  `psycopg2.errors.NotNullViolation: null value in column "inventory_location_id" of relation "fsm_location" violates not-null constraint
`

Some previous Odoo versions the required=True on the field only affected the frontend, but a couple of Odoo versions a go, it creates a constraint in the database.

At the moment I still see that only enable the required in the fronted would be the best solution. There are more modules that trigger this error.

I implemented the pre_init hook, to fill the available fsm.locations in the default stock location

**Comment by max3903** [comment]
@gbrito-erpopen When the `fsm.location` is created after the installation of `fieldservice_stock`, the default value for the `inventory_location_id` field should be used.

**Comment by ghost** [comment]
@max3903 @brian10048 for review :)

**Review by max3903 — APPROVED** [review]

**Pull request merged**
