### PR TITLE
[14][FIX] fieldservice_recurring: fsm_order_ids should be readonly

### PR DESCRIPTION
**Pull request by hparfr**
in the UI, it should not be allowed to select orders to be added to recurring.

### CODE REVIEW

**Comment by brian10048** [comment]
@hparfr I don't intend to add a new order to a recurring in the UI, but it is helpful to be able to edit an existing order from the view of the recurring.  For example to edit the assigned worker.

**Comment by hparfr** [comment]
Fixed, the widget was not the good one, so create=false was not effective.

I allowed to unlink() from recurring.

**Review by brian10048 — APPROVED** [review]
Tested on runboat

**Pull request merged**
