### PR TITLE
[ADD][12.0] fieldservice_geoengine

### PR DESCRIPTION
**Pull request by murtuzasaleh**
WIP

### CODE REVIEW

**Comment by max3903** [comment]
@murtuzasaleh You need to install postgis to create the extension:
https://github.com/OCA/field-service/blob/11.0/.travis.yml#L16

Please remove postgres 9.5 while editing `.travis.yml`

**Comment by murtuzasaleh** [comment]
@max3903 In v11 [GeoCode Location](https://github.com/OCA/field-service/pull/170/files#diff-22ce73c8ed1ac6e936a86d492a075c7dR16) button code is not added in fsm.order.

I found an error when I click on it, Can I create a method and call odoo base method?

**Comment by murtuzasaleh** [comment]
@max3903 Is it fine?

`
@api.multi
def geo_localize(self):
       for order in self:
            order.person_id.partner_id.geo_localize()
`

**Comment by max3903** [comment]
Should be the location_id:
```
order.location_id.partner_id.geo_localize()
```

**Comment by murtuzasaleh** [comment]
@max3903 @osi-scampbell Can you please review this PR.

**Review by max3903 — APPROVED** [review]
LGTM. No Test.

**Comment by murtuzasaleh** [comment]
@max3903 Everything is ok in my local system why Travis is failed.

**Comment by max3903** [comment]
@murtuzasaleh Others modules are failing: https://travis-ci.org/OCA/field-service/jobs/521789966#L7786

**Review by osi-scampbell — APPROVED** [review]

**Pull request merged**
