### PR TITLE
[16.0][MIG] fieldservice_stock_request: Migration to 16.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 16.0

cc https://github.com/APSL 153666

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/field-service/issues/963

Depends on:

- [stock_request_direction ] https://github.com/OCA/stock-logistics-request/pull/20
- [stock_request_picking_type ] https://github.com/OCA/stock-logistics-request/pull/21

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Working correctly, checked in runboat

**Review by celm1990 — APPROVED** [review]
LGTM tested functionally

**Comment by miquelalzanillas** [comment]
Hi @max3903 , is this ready to merge? We are interested in to start migration to v17.

**Comment by max3903** [comment]
@miquelalzanillas Dependencies need to be migrated first...

**Comment by peluko00** [comment]
> @miquelalzanillas Dependencies need to be migrated first...

Just merged, it's ready

**Comment by peluko00** [comment]
Ready for merge @max3903

**Comment by max3903** [comment]
@peluko00 This is not ready to merge. There are still errors.

**Comment by peluko00** [comment]
> @peluko00 This is not ready to merge. There are still errors.

Which errors?

**Comment by max3903** [comment]
@peluko00 Tests are failing.

**Comment by peluko00** [comment]
> /ocabot merge nobump

Seems like not working

**Pull request merged**
